<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930093750 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial du site';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE certification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, subtitle VARCHAR(160) DEFAULT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, school VARCHAR(160) DEFAULT NULL, start_year INT NOT NULL, end_year INT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, company VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, job_title VARCHAR(160) NOT NULL, job_subtitle VARCHAR(160) DEFAULT NULL, location VARCHAR(120) DEFAULT NULL, intro TEXT DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, malt_url VARCHAR(255) DEFAULT NULL, skills JSON NOT NULL, hobbies JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, title VARCHAR(160) NOT NULL, client VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, technologies JSON NOT NULL, position INT NOT NULL, published BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE certification');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE "user"');
    }
}
